FROM golang:1.20 AS desafioGo

WORKDIR /usr/src/app

COPY ./app/* ./
RUN go mod download && go mod verify

COPY . . 
RUN go build -v -o /usr/local/bin/app ./...

FROM scratch

COPY --from=desafioGo /usr/local/bin/app .

CMD ["./app"]